---
title: 'Raw report: Birth weight'
author: "Cyril Matthey-Doret"
date: "November 3, 2016"
output: pdf_document
---

```{r setup, include=F}
setwd ("/home/cyril/Documents/Master/sem_1/Data_analysis/data/")
library(ggplot2);library(gridExtra)
birth_weight<-read.table("birtweigth_study.txt", sep= " ")
row.names(birth_weight) <- NULL
birth_weight$lwt <- birth_weight$lwt*0.45359237
birth_weight$bwt <- birth_weight$bwt/1000
birth_plotter <- function(df){
  plotlist <- list()
  count <- 1
  for(c in colnames(df)){
    if(is.numeric(df[1,c])){
      plotlist[[count]] <-ggplot(data=df)+
      geom_point(aes(x=df[,c],y=df$bwt))+
        theme_bw()
      print(paste(c, "points",sep=" "))
      plotlist[[count]]
    } else{
    plotlist[[count]] <-ggplot(data=birth_weight)+
      geom_boxplot(aes(x=df[,c],y=df$bwt))+
      theme_bw()
    print(paste(c, "box",sep=" "))
    print(plotlist[[count]])
    }
    count <- count + 1
  }
  return(plotlist[[count]])
}

plotlist <- list()
  count <- 1
  for(c in colnames(df)){
    print(count)
    if(is.numeric(df[1,c])){
      plotlist[[count]] <-ggplot(data=df)+
      geom_point(aes(x=df[,c],y=df$bwt))+
        theme_bw()
    } else{
    plotlist[[count]] <-ggplot(data=df)+
      geom_boxplot(aes(x=df[,c],y=df$bwt))+
      theme_bw()
    }
    count <- count + 1
  }

```

```{r data_check, include =F}
grid.arrange(grobs=birth_plotter(birth_weight),ncol=2)
```

